config/routes.rb
Rails.application.routes.draw do
  resources "patients", only: [:index, :show], id: /[^\/]+/
  resources "handoffs", only: [:index, :show, :create, :destroy]
  resources "annotations", only: [:create, :update, :destroy]
  resources "shares", only: [:create, :destroy]

  #override devise's new_user_registration path before it is set by devise so that unsigned in attempts to access protected pages redirect the user to the app root
  get '/users/sign_in', to: redirect('/'), as: 'new_user_registration'

  devise_for :users

  root "welcome#index"

  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_filter :authenticate_user!

  def index
    if user_signed_in?
      redirect_to handoffs_path
    end
  end

  def about
  end

  def contact
  end
end

app/views/welcome/about.html.erb
<div class="col-md-10 col-md-offset-1">
  <div class="well">
  <h3>About Handoff</h3>
    <h4>Overview</h4>
    <p>
      Handoff is a platform for next generation care coordination. Using Handoff,
      providers can collaboratively annotate electronic medical records
      to ensure efficient and continuous care. Handoff is meant to free care
      providers from the phone calls, texts, and other forms of informal communication
      that are currently used to facilitate care coordination.
    </p>

    <h4>How it Works</h4>
    <p>
      Handoff allows users to view and annotate patient records that are formatted
      with <a href="http://hl7.org/fhir/">HL7's FHIR API</a>.
      The resulting annotated record is called a 'handoff' and the user is able
      to share the handoff with other providers, who may also contribute to the
      annotations and discussion.
    </p>

    <p>
      To preserve the security and privacy of patient records, Handoff does not
      store medical records locally. Instead, Handoff fetches the external FHIR
      record and then combines the record with the locally stored annotations.
      In this way, annotations made in Handoff never become a permanent part of
      the FHIR-accessible patient record. Each handoff stores transient
      communication that expires after a period of inactivity by all collaboraters.
    </p>

    <h4>Why Handoff?</h4>
    <p>
      Why not call, text, or dictate a message to my colleageus instead? Calling
      your colleague requires coordination that is rarely possible during the
      medical professional's work schedule. Additonally, listening and
      responding to voice mails is unorganized and time-consuming. Text messages
      can violate patient privacy, and even secure text messaging comes with
      little context within a patient's care plan. Finally, dictations provide
      multiple layers of transcribing and delivery that take hours or days to
      reach the intended recipient. With Handoff, communication is instantaneous
      yet unobtrusive; annotations are linked to the source of information (the
      patient's medical record), and communication will <i>never</i> become part
      of the patient's medical record.
    </p>
  </div>
</div>

app/views/welcome/contact.html.erb
<div class="col-md-11">
<div class="well">
<h3>Credits</h3>
<p>
Handoff was developed by team 'ML Rehab' for the Spring 2015 offering of Georgia Tech's CS 6440 - Health Informatics course.
</p>
<h4>Team Members</h4>
<ul>
  <li>Edward Anderson</li>
  <li>Corey Featherly</li>
  <li>Kyle McIntyre</li>
  <li>Michael Wytock</li>
  <li>Jonathan Young</li>
</ul>
</div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="well">
      <h1>Welcome to Handoff</h1>
    <p>
      Handoff is a platform for next generation care coordination. Using Handoff,
      providers can collaboratively annotate electronic medical records
      to ensure efficient and continuous care. Handoff is meant to free care
      providers from the phone calls, texts, and other forms of informal communication
      that are currently used to facilitate care coordination.
    </p>
      <%= link_to 'Learn more!', about_path %>
    </div>
  </div>
</div>

<div class="row text-center">
  <h1>
    Try It!<br>
    <small><strong>Log in</strong> as a demo user with one of these roles:</small>
  </h1>

  <div class="col-sm-4">
    <button class="btn btn-success btn-lg prefill-login" data-user-email="dr-johnson@pcp.local">Initiator</button>
    <blockquote><small>
      A doctor whose account is configured with access to all electronic medical records provided by his practice's FHIR API.
    </small></blockquote>
  </div>

  <div class="col-sm-4">
    <button class="btn btn-primary btn-lg prefill-login" data-user-email="dr-peters@cardio.med">Collaborator 1</button>
    <blockquote><small>
      A doctor at a neighboring practice who often receives the Initiator's patients.
    </small></blockquote>
  </div>

  <div class="col-sm-4">
    <button class="btn btn-primary btn-lg prefill-login" data-user-email="dr-erickson@pulmo.med">Collaborator 2</button>
    <blockquote><small>
      An expert physician who the Initiator often goes to for advice when making tough calls regarding a patient, for patients that have given consent.
    </small></blockquote>
    </div>
</div>

<div class="row hidden">
  <div class="col-sm-2 col-sm-offset-5">
    <h2>Log in</h2>

    <%= form_for(User.new, url: session_path('user')) do |f| %>
      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email %>
      </div>

      <div class="field">
        <%= f.label :password %><br />
        <%= f.password_field :password, autocomplete: "off" %>
      </div>

      <div class="actions">
        <%= f.submit "Log in", class: 'btn btn-default' %>
      </div>
    <% end %>
  </div>
</div>