config/routes.rb
Rails.application.routes.draw do
  resources "patients", only: [:index, :show], id: /[^\/]+/
  resources "handoffs", only: [:index, :show, :create, :destroy]
  resources "annotations", only: [:create, :update, :destroy]
  resources "shares", only: [:create, :destroy]

  #override devise's new_user_registration path before it is set by devise so that unsigned in attempts to access protected pages redirect the user to the app root
  get '/users/sign_in', to: redirect('/'), as: 'new_user_registration'

  devise_for :users

  root "welcome#index"

  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'

end

app/models/api/patient.rb
class API
  class Patient
    RPATH_CONST = "Patient/"

    def all
      results = HTTParty.get("#{BASE_URL_CONST}#{RPATH_PAT_CONST}#{RPATH_PARAMS_CONST}#{RPATH_COUNT_100_CONST}")
      results_hash = JSON.parse(results.body)
      patients = results_hash["entry"].map do |patient_data|
        extract_object_from_data(patient_data["content"])
      end
    end

    def update(patient)
      results = HTTParty.get("#{BASE_URL_CONST}#{RPATH_PAT_CONST}#{patient.pid}#{RPATH_PARAMS_CONST}")
      results_hash = JSON.parse(results.body)
      patient.fname = results_hash["name"][0]["given"].first
      patient.lname = results_hash["name"][0]["family"].first
      patient
    end

    def find(pid)
      results = HTTParty.get("#{BASE_URL_CONST}#{RPATH_PAT_CONST}#{pid}#{RPATH_PARAMS_CONST}")
      results_hash = JSON.parse(results.body)
      extract_object_from_data(results_hash)
    end

    private

    def extract_object_from_data(patient_data)
      data = ResponseData.new(patient_data)
      pid        = data.get(0, "identifier", "array", "value")
      name_first = data.get(0, "name", "array", "given", "array")
      name_last  = data.get(0, "name", "array", "family", "array")
      Patient.new(pid, name_first, name_last)
    end
  end
end

app/models/patient.rb
class Patient
  include ActiveModel::Model

  attr_accessor :fname, :lname, :pid, :fhir, :observations, :birthday
  attr_writer :conditions, :medications
  alias :to_param :pid

  class << self
    def all
      api.all_patients
    end
  end

  def initialize(pid, fname = nil, lname = nil)
    @pid = pid
    @fname = fname
    @lname = lname
  end

  def full_name
    api.update_patient(self) unless @got_full_name || @fname.present? && @lname.present?
    @got_full_name = true
    "#{@fname} #{@lname}"
  end

  def weight
    body_weight_observation = observations.select { |observation| observation.code_display == "Body Weight"}
    Weight.new(body_weight_observation).to_s
  end

  def birthday
    FakeBirthdate.new(patient).to_s
  end

  def age
    birthday_object = Time.parse(birthday)
    age = Date.today.year - birthday_object.year
  end

  def height
    height_observation = observations.select { |observation| observation.code_display == "Body Height" }
    Height.new(height_observation).to_s
  end

  def observations
    cache_assessments(:observations) do
      api.update_patient_assessments(:observations, self)
    end
  end

  def conditions
    cache_assessments(:conditions) do
      api.update_patient_assessments(:conditions, self)
    end
  end

  def medications
    cache_assessments(:medications) do
      api.update_patient_assessments(:medications, self)
    end
  end

  private

  def api
    @api ||= API.new
  end

  def cache_assessments(type)
    @cached_assessments ||= {}
    return @cached_assessments[type] if @cached_assessments.key?(type)
    @cached_assessments[type] = yield
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  def index
    @directory = Patient.all
  end

  def show
    @patient_id = params[:id]
    @patient_data = Patient.new(@patient_id)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
  def self.grouped_and_sorted(assessments)
    assessments.sort_by!(&:date).group_by(&:key)
  end
end

app/views/patients/_condition.html.erb
<%
condition = conditions[0]

historyId = SecureRandom.uuid

if conditions.size > 1
  @datatableIds.push(historyId)
end
%>

<div id="<%= condition.id %>" class="annotatable">
  <a class="anchor" name="<%= condition.id %>-link"></a>
  <div class="well well-sm">
    <%= render 'handoffs/annotate_button' %>

    <% if conditions.size > 1 %>
    <button class="btn btn-default btn-annotate pull-right" title="View prior occurrences of condition" data-toggle="modal" data-target="#<%= "#{historyId}Modal" %>">
      <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
    </button>
    <% end %>

    <h4><%= condition.value %></h4>
    <table class="table">
      <tr>
        <th>Onset</th>
        <th>Status</th>
        <th>Code</th>
      </tr>
      <tr>
        <td><%= condition.onset_date != nil ? condition.onset_date.to_date : "" %></td>
        <td><%= condition.status %></td>
        <td><%= condition.code %></td>
      </tr>
    </table>
  </div>
  <div class="modal fade" id="<%= "#{historyId}Modal" %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%= condition.value %> History</h4>
        </div>
        <div class="modal-body">
          <table id="<%= historyId %>" class="display">
            <thead>
              <tr>
                <th>Onset</th>
                <th>Status</th>
                <th>Code</th>
              </tr>
            </thead>
            <tbody>
              <% conditions.each do |c| %>
                <tr>
                  <td><%= c.onset_date != nil ? c.onset_date.to_date : "" %></td>
                  <td><%= c.status %></td>
                  <td><%= c.code %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/patients/_observation.html.erb
<%
observation = observations[0]

historyId = SecureRandom.uuid

if observations.size > 1
  @datatableIds.push(historyId)
end
%>
<div id="<%= observation.id %>" class="annotatable">
  <a class="anchor" name="<%= observation.id %>-link"></a>
  <div class="well well-sm">
    <%= render 'handoffs/annotate_button' %>

    <% if observations.size > 1 %>
    <button class="btn btn-default btn-annotate pull-right" title="View older observations" data-toggle="modal" data-target="#<%= "#{historyId}Modal" %>">
      <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
    </button>
    <% end %>

    <h4><%= observation.code_display %></h4>
    <table class="table">
      <tr>
        <% if observation.value != nil %>
        <th>Value</th>
        <th>Units</th>
        <% else %>
        <th>Result</th>
        <% end %>
        <th>Date</th>
      </tr>
      <tr>
        <% if observation.value != nil %>
        <td><%= observation.value %></td>
        <td><%= observation.units %></td>
        <% else %>
        <td><%= observation.display.html_safe %></td>
        <% end %>
        <td><%= observation.date != nil ? observation.date.to_date : "" %></td>
      </tr>
    </table>
  </div>
  <div class="modal fade" id="<%= "#{historyId}Modal" %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%= observation.code_display %> History</h4>
        </div>
        <div class="modal-body">
          <table id="<%= historyId %>" class="display">
            <thead>
              <tr>
                <% if observation.value != nil %>
                <th>Value</th>
                <th>Units</th>
                <% else %>
                <th>Result</th>
                <% end %>
                <th>Date</th>
              </tr>
            </thead>
            <tbody>
            <% observations.each do |obs| %>
              <tr>
                <% if observation.value != nil %>
                <td><%= obs.value %></td>
                <td><%= obs.units %></td>
                <% else %>
                <td><%= obs.display.html_safe %></td>
                <% end %>
                <td><%= obs.date != nil ? obs.date.to_date : "" %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/patients/_patient.html.erb
<% @datatable_ids = []

resource_map = {}

@patient_data.conditions.each do |condition|
  resource_map[condition.id] = condition.value
end

@patient_data.medications.each do |prescription|
  resource_map[prescription.id] = prescription.value
end

@patient_data.observations.each do |observation|
  resource_map[observation.id] = observation.code_display
end

%>
<div class="row">
  <div class="col-md-2 col-md-offset-1 fixed">
    <div class="well">
      <div class="text-center">
        <h3><%= @patient_data.full_name %></h3>
        <hr />
        <%= image_tag("unknown-gender-avatar.png", :alt => "Patient photo not available") %>
        <hr />
       </div>
      <ul class="nav nav-pills nav-stacked patient-nav">
        <% if @handoff %>
          <li><a href="#handoff">Handoff Summary</a></li>
        <% end %>
        <li><a href="#overview">Patient Summary</a></li>
        <li><a href="#conditions">Conditions</a></li>
        <li><a href="#prescriptions">Prescriptions</a></li>
        <li><a href="#observations">Observations</a></li>
      </ul>
      <% if @handoff.nil? %>
        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#handoffModal">
          Start a Handoff
        </button>
      <% else %>
        <button type="button" class="btn btn-success btn-block" data-toggle="modal" data-target="#shareModal">
          Share this Handoff
        </button>
      <% end %>
    </div>
  </div>
  <div class="col-md-6 col-md-offset-3">
    <% if @handoff %>
      <%
        shared_with = ""
         @handoff.shares.each do |share|
           shared_with += (share.user_id == current_user.id ? "You" : User.find(share.user_id).email) + ", "
         end
        shared_with = shared_with[0...-2]

        uniquely_annotated = @handoff.annotations.map { |a| a.resource_id }
        uniquely_annotated = uniquely_annotated.uniq
      %>

      <a class="anchor" name="handoff"></a>
      <div class="panel panel-default handoff-summary">
        <div class="panel-heading">
          Handoff Summary
        </div>
        <div class="panel-body">
          <dl class="dl-horizontal">
            <dt>Name:</dt>
            <dd><%= @handoff.name %></dd>
            <dt>Reason:</dt>
            <dd><%= @handoff.description %></dd>
            <dt>Initiated By:</dt>
            <dd><%= User.find(@handoff.creator_id).email %> on <%= @handoff.created_at.strftime("%B %d, %Y")  %></dd>
            <dt>Last Modified:</dt>
            <dd><%= @handoff.last_modified().strftime("%B %d, %Y at %I:%M %p") %></dd>
            <dt>Shared With:</dt>
            <dd><%= shared_with %></dd>
          </dl>

          <% if uniquely_annotated.size > 0 %>
            <h5>Quick Links</h5>
            <ul>
              <% uniquely_annotated.each do |resource_id| %>
                <li>Comments on <a href="#<%= resource_id %>-link"><%= resource_map[resource_id] %></a></li>
              <% end %>
            <ul>
          <% end %>
        </div>
      </div>
    <% end %>
    <a class="anchor" name="overview"></a>
    <div class="panel panel-default">
      <div class="panel-heading">
        Patient Summary
      </div>
      <div class="panel-body">
        <dl class="dl-horizontal">
          <dt>Name:</dt>
          <dd><%= @patient_data.full_name %></dd>
          <dt>Birthday:</dt>
          <dd><%= @patient_data.birthday %> (<%= @patient_data.age %> years old)</dd>
          <dt>Height:</dt>
          <dd><%= @patient_data.height %></dd>
          <dt>Weight:</dt>
          <dd><%= @patient_data.weight %></dd>
        </dl>
      </div>
    </div>

    <a class="anchor" name="conditions"></a>
    <div class="panel panel-default">
      <div class="panel-heading">
        Conditions
      </div>
      <div class="panel-body">
        <% PatientsHelper.grouped_and_sorted(@patient_data.conditions).each do |key, conditions| %>
          <%= render partial: "patients/condition", locals: {conditions: conditions} %>
        <% end %>
      </div>
    </div>

    <a class="anchor" name="prescriptions"></a>
    <div class="panel panel-default">
      <div class="panel-heading">
        Prescriptions
      </div>
      <div class="panel-body">
        <% PatientsHelper.grouped_and_sorted(@patient_data.medications).each do |key, medications| %>
          <%= render partial: "patients/prescription", locals: {prescriptions: medications} %>
        <% end %>
      </div>
    </div>

    <a class="anchor" name="observations"></a>
    <div class="panel panel-default">
      <div class="panel-heading">
        Observations
      </div>
      <div class="panel-body">
        <% PatientsHelper.grouped_and_sorted(@patient_data.observations).each do |key, observations| %>
          <%= render partial: "patients/observation", locals: {observations: observations} %>
        <% end %>
      </div>
    </div>

  </div>
  <div class="col-md-3">
    <%= render 'annotations' if @handoff %>
  </div>
</div>

<% if @handoff.nil? %>
  <div class="modal fade" id="handoffModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%= form_for Handoff.new do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="handoffModalLabel">Create Handoff for <%= "#{@patient_data.full_name}"%></h4>
          </div>
          <div class="modal-body">
            <table class="table">
              <tr>
                <td><%= f.label :name %></td>
                <td><%= f.text_field :name, :value => "#{@patient_data.full_name} - #{DateTime.now.to_date}", :size => 40 %></td>
              </tr>
              <tr>
                <td><strong>Reason for Handoff</strong></td>
                <td><%= f.text_area  :description, :size => "40x5" %></td>
              </tr>
            </table>
            <%= f.hidden_field :creator_id, :value => current_user.id %>
            <%= f.hidden_field :patient_id, :value => @patient_data.pid %>
          </div>
          <div class="modal-footer">
            <%= f.submit "Create Handoff", class: "btn btn-primary" %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% else %>
  <div class="modal fade" id="shareModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <%
          @share  = Share.new()
          current_ids = @handoff.shares.map { |s| s.user_id }
          possible_users = User.where("id not in (?)", current_ids)
          select_options = possible_users.map { |u| [u.email, u.id] }
        %>

        <%= form_for @share do |f| %>
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="shareModalLabel">Share with Collaborators</h4>
          </div>
          <div class="modal-body">
            <p>
        <b>Disclaimer:</b>
      </p>

      <p>
        Handoff records contain privileged and
              confidential information, including protected health
              information (PHI) which is protected by federal and
              state privacy laws. Handoff records are legally
              required to only be viewed by the person(s) that have
              been explicitly authorized to do so by the patient
        via a signed HIPAA release form.
      </p>

      <p>
        By using Handoff, you agree to release the Handoff application
        and the associates of the Handoff application of all
        liability related to the storage, transmission
        (including sharing), and processing (including viewing)
        of sensitive information, including patient data. By
        using Handoff you assume all liability related to the
        storage, transmission (including sharing), and
        processing (including viewing) of the sensitive
        information, including patient data, that you view
        and/or share.
      </p>

            <p>
        If you receive a handoff granting you access to patient data for
        which you are not authorized, you:
        <ul>
    <li>Are hereby notified that any review,
      dissemination, distribution, duplication, or
      accessing of that Handoff patient data is
      strictly prohibited, and;</li>
    <li>Must destroy any copies of that
      information, and;</li>
    <li>Must contact the sender notifying them
      that you are not authorized to access the
      information they have shared with you.</li>
        </ul>
      </p>

      <p>
        For additional information on HIPAA requirements and
        restrictions, see <a href="http://www.hhs.gov/ocr/privacy/hipaa/administrative/combined/hipaa-simplification-201303.pdf">45 CFR Parts 160, 162, and 164</a>.<br>
      </p>

           <%= f.hidden_field :handoff_id, :value => @handoff.id %>
           <p>
             <%= f.select :user_id, select_options %>
           </p>
        </div>
          <div class="modal-footer">
            <%= f.submit "Share Handoff", class: "btn btn-primary" %>
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

<% content_for :body_end do %>
  <script type="text/javascript">
  <% @datatable_ids.each do |id| %>
 $(document).ready(function() {
    $('<%= "##{id}" %>').dataTable({
      "bLengthChange": false,
      "bFilter": false,
      "iDisplayLength": 50
    });
} );

  <% end %>
  </script>
<% end %>

app/views/patients/_prescription.html.erb
<%
prescription = prescriptions[0]

historyId = SecureRandom.uuid

if prescriptions.size > 1
  @datatableIds.push(historyId)
end
%>

<div id="<%= prescription.id %>" class="annotatable">
  <a class="anchor" name="<%= prescription.id %>-link"></a>
  <div class="well well-sm">
    <%= render 'handoffs/annotate_button' %>

    <% if prescriptions.size > 1 %>
    <button class="btn btn-default btn-annotate pull-right" title="View older prescriptions" data-toggle="modal" data-target="#<%= "#{historyId}Modal" %>">
      <span class="glyphicon glyphicon-list-alt" aria-hidden="true"></span>
    </button>
    <% end %>

    <h4><%= prescription.value %></h4>
    <table class="table">
      <tr>
        <th>Prescriber</th>
        <th>Date</th>
        <th>Dosage Value</th>
        <th>Dosage Units</th>
      </tr>
      <tr>
        <td><%= prescription.prescriber %></td>
        <td><%= prescription.written_date != nil ? prescription.written_date.to_date : "" %></td>
        <td><%= prescription.dosage_value %></td>
        <td><%= prescription.dosage_units %></td>
      </tr>
    </table>
  </div>
  <div class="modal fade" id="<%= "#{historyId}Modal" %>" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
           <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
           <h4 class="modal-title"><%= prescription.value %> History</h4>
        </div>
        <div class="modal-body">
          <table id="<%= historyId %>" class="display">
            <thead>
              <tr>
                <th>Prescriber</th>
                <th>Date</th>
                <th>Dosage Value</th>
                <th>Dosage Units</th>
              </tr>
            </thead>
            <tbody>
              <% prescriptions.each do |pre| %>
                <tr>
                  <td><%= pre.prescriber %></td>
                  <td><%= pre.written_date != nil ? pre.written_date.to_date : "" %></td>
                  <td><%= pre.dosage_value %></td>
                  <td><%= pre.dosage_units %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/patients/index.html.erb
<div class="col-md-10 col-md-offset-1">
  <h1>Patients</h1>
  <table id="patients" class="display">
    <thead>
      <tr>
        <th>Patient Name</th>
        <th>Patient ID</th>
        <th>Patient Birthday</th>
      </tr>
    </thead>
    <tbody>
    <% @directory.each do |a_patient| %>
      <tr>
        <td><%= link_to a_patient.full_name, patient_path(a_patient) %></td>
        <td><%= a_patient.pid %></td>
        <td><%= a_patient.birthday %> (<%= a_patient.age %> years old)</td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<% content_for :body_end do %>
  <script type="text/javascript">
$(document).ready(function() {
    $('#patients').dataTable({
      "bLengthChange": false,
      "iDisplayLength": 50
    });
} );
  </script>
<% end %>

app/views/patients/show.html.erb
<%= render partial: "patient" %>