config/routes.rb
Rails.application.routes.draw do
  resources "patients", only: [:index, :show], id: /[^\/]+/
  resources "handoffs", only: [:index, :show, :create, :destroy]
  resources "annotations", only: [:create, :update, :destroy]
  resources "shares", only: [:create, :destroy]

  #override devise's new_user_registration path before it is set by devise so that unsigned in attempts to access protected pages redirect the user to the app root
  get '/users/sign_in', to: redirect('/'), as: 'new_user_registration'

  devise_for :users

  root "welcome#index"

  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Handoff</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default navbar-fixed-top" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
      </button>
      <%= link_to 'Handoff', root_url, class: 'navbar-brand' %>
    </div>
    <nav class="collapse navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
        <li>
          <%= link_to "Patient Records", patients_path %>
        </li>
        <% end %>
        <li>
          <%= link_to "About", about_path %>
        </li>
      </ul>
      <% if user_signed_in? %>
        <p class="navbar-text">
          Logged in as <%= current_user.email %>
          (<%= link_to 'log out', destroy_user_session_path, method: :delete %>)
        </p>
      <% end %>
    </nav>
  </div>
</nav>

<div class="container-fluid">

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>

</div>

<hr>
<div class="container">
  <p class="text-muted credit text-center">Created by team <%= link_to "ML Rehab", contact_path %></p>
</div>
<br>

  <%= javascript_include_tag 'application' %>
  <%= yield :body_end %>
</body>
</html>